### Q1. If you have any, what are your choices for increasing the comparison between different figures on the same graph?

We can use matplotlib using plt.show() 

we can also use seaborn FacetGrid

### Q2. Can you explain the benefit of compound interest over a higher rate of interest that does not compound after reading this chapter?

### Q3. What is a histogram, exactly? Name a numpy method for creating such a graph.

The histogram is a popular graphing tool. It is used to summarize discrete or continuous data that are measured on an interval scale. It is often used to illustrate the major features of the distribution of the data in a convenient form.


numpy.histogram() method which represents the frequency of data distribution in the graphical form.

### Q4. If necessary, how do you change the aspect ratios between the X and Y axes?

in matplotlib we can use `axes.set_aspect()`

### Q5. Compare and contrast the three types of array multiplication between two numpy arrays: dot product, outer product, and regular multiplication of two numpy arrays.

In [3]:
import numpy as np

array1 = np.array([[6,2], [10,5]])
array2 = np.array([[2,5], [2,7]])

print(array1)
print(array2)

[[ 6  2]
 [10  5]]
[[2 5]
 [2 7]]


In [4]:
np.outer(array1, array2)

array([[12, 30, 12, 42],
       [ 4, 10,  4, 14],
       [20, 50, 20, 70],
       [10, 25, 10, 35]])

In [5]:
np.dot(array1, array2)

array([[16, 44],
       [30, 85]])

In [6]:
array1 * array2

array([[12, 10],
       [20, 35]])

### Q6. Before you buy a home, which numpy function will you use to measure your monthly mortgage payment?

numpy.pmt()

### Q7. Can string data be stored in numpy arrays? If so, list at least one restriction that applies to this data.

yes, we can store strings in numpy array, 

Numpy arrays are Homogeneous. NumPy arrays can only hold elements of one datatype, so if we add an integer or a float value it will be converted to string datatype

In [12]:
x = np.array(["Hello", 10])

type(x[1])

numpy.str_