### Q1. What are the benefits of the built-in array package, if any?

In [1]:
import array

Arrays are similar to lists. The main difference is that arrays can store only one type of elements; whereas, lists can store different types of elements. When dealing with a huge number of elements, arrays use less memory than lists and they offer faster execution than lists.

The size of the array is not fixed in Python. Hence, we need not specify how many elements we are going to store into an array in the beginning.

Arrays can grow or shrink in memory dynamically (during runtime).

Arrays are useful to handle a collection of elements like a group of numbers or characters.

Methods that are useful to process the elements of any array are available in 'array' module.

### Q2. What are some of the array package's limitations?

In [2]:
dir(array)

['ArrayType',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_array_reconstructor',
 'array',
 'typecodes']

Only very limited functions are available in python built in arrays

### Q3. Describe the main differences between the array and numpy packages.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python's built-in sequences

### Q4. Explain the distinctions between the empty, ones, and zeros functions.

The `empty()` function of NumPy creates an uninitialized array having shape and dtype as given to the empty() function.

The `zeros()` function of NumPy creates a ndarray initialized with 0 values having shape and dtype as given as input.

The `ones()` function of NumPy creates a ndarray initialized with 1 having shape and dtype as given as input.

### Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

Here the callable argument is `function`

function: 
            
            The function is called with N parameters, where N is the rank of shape. Each parameter represents the coordinates of the array varying along a specific axis. For example, if shape were (2, 2), then the parameters would be array([[0, 0], [1, 1]]) and array([[0, 1], [0, 1]])

### Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

In [1]:
import numpy as np

In [4]:
x = np.zeros([2,3])

In [5]:
x + 10

array([[10., 10., 10.],
       [10., 10., 10.]])

Element wise addition is happend

### Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

In [8]:
x = np.ones([2,3])

x+=10

x

array([[11., 11., 11.],
       [11., 11., 11.]])

In [10]:
x*=100
x

array([[110000., 110000., 110000.],
       [110000., 110000., 110000.]])

### Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

### Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

In [12]:
x = np.ones([3,3])

y = np.ones([3,3])

x + y

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [13]:
x*y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

The condition for cobining two arrays are both has to be in same shape and dimension

### Q10. What is the best way to use a Boolean array to mask another array?

In [14]:
A = 10 * np.random.random((3,3))
A

array([[6.62130364, 2.3468978 , 5.51509096],
       [2.02991119, 4.64153811, 1.32952951],
       [3.70662941, 0.67421639, 9.28348779]])

In [16]:
mask = A<4

mask

array([[False,  True, False],
       [ True, False,  True],
       [ True,  True, False]])

In [17]:
A[mask] 

array([2.3468978 , 2.02991119, 1.32952951, 3.70662941, 0.67421639])

### Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

In [37]:
speed = [86,87,88,86,87,85,86]

np.std(speed)

0.9035079029052513

In [35]:
from statistics import stdev

stdev(speed)

0.9759000729485332

In [38]:
from scipy import stats

stats.tstd(speed)

0.9759000729485332

### 12. What is the dimensionality of a Boolean mask-generated array?

One dimension